# Generated by Django 3.1.7 on 2021-03-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
